apiVersion: v1
kind: ConfigMap
metadata:
  name: optimize-env-vars
  namespace: camunda8-dev
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: optimize
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: optimize
data:
  CAMUNDA_OPTIMIZE_API_AUDIENCE: optimize-api
  CAMUNDA_OPTIMIZE_ENTERPRISE: "true"
  CAMUNDA_OPTIMIZE_API_JWTSETURI: https://camunda.example.com/auth/realms/camunda-platform/protocol/openid-connect/certs # kpt-set: https://${keycloak-domain}/auth/realms/camunda-platform/protocol/openid-connect/certs
  CAMUNDA_OPTIMIZE_CONTEXT_PATH: /optimize
  CAMUNDA_OPTIMIZE_IDENTITY_AUDIENCE: optimize-api
  CAMUNDA_OPTIMIZE_IDENTITY_CLIENTID: optimize
  CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_BACKEND_URL: http://camunda-keycloak/auth/realms/camunda-platform # kpt-set: ${keycloak-backend}/auth/realms/camunda-platform
  CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL: https://camunda.example.com/auth/realms/camunda-platform # kpt-set: https://${keycloak-domain}/auth/realms/camunda-platform
  CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED: "false"
  CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN: "true"
  CAMUNDA_OPTIMIZE_ZEEBE_ENABLED: "true"
  CAMUNDA_OPTIMIZE_ZEEBE_PARTITION_COUNT: "3"
  #  JDK_JAVA_OPTIONS: -Dlogging.level.root=info -Djavax.net.ssl.trustStore=/etc/ssl/camunda/trust-store.jks -Djavax.net.ssl.trustStorePassword=demodemo
  OPTIMIZE_ELASTICSEARCH_HOST: elasticsearch-master
  OPTIMIZE_ELASTICSEARCH_HTTP_PORT: "9200"
  SPRING_PROFILES_ACTIVE: ccsm
