kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'
resources:
- zeebe-gateway-deployment.yaml
- zeebe-gateway-service.yaml
- zeebe-gateway-service-account.yaml
- zeebe-gateway-configmap.yaml
- zeebe-gateway-env-vars.yaml
- zeebe-gateway-startup.yaml
