kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'
resources:
- camunda8-psp.yaml
- camunda8-role.yaml
- camunda8-rolebinding.yaml
