apiVersion: v1
kind: ConfigMap
metadata:
  name: connectors-env-vars
  namespace: camunda8-dev
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: connectors
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: connectors
data:
  JDK_JAVA_OPTIONS: -Dlogging.level.root=info -Djdk.httpclient.HttpClient.log=info -Djavax.net.ssl.trustStore=/etc/ssl/camunda/trust-store.jks -Djavax.net.ssl.trustStorePassword=demodemo
  CAMUNDA_OPERATE_CLIENT_CLIENT-ID: connectors
  CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM: camunda-platform
  CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL: http://camunda-keycloak.camunda8-dev.svc.cluster.local
  CAMUNDA_OPERATE_CLIENT_URL: http://camunda-operate.camunda8-dev.svc.cluster.local/operate
  ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS: camunda-zeebe-gateway:26500 # kpt-set: ${zeebe-host}
  ZEEBE_CLIENT_SECURITY_PLAINTEXT: "true"
