apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hashicorp-vault-agent-injector-binding
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: hashicorp-vault
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hashicorp-vault-agent-injector-clusterrole
subjects:
- kind: ServiceAccount
  name: hashicorp-vault-agent-injector
  namespace: camunda8-dev