apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'
resources:
- modeler-websockets-configmap.yaml
- modeler-websockets-deployment.yaml
- modeler-websockets-service.yaml
- modeler-websockets-service-account.yaml
- modeler-websockets-env-vars.yaml
- modeler-websockets-envoy-filter.yaml
