apiVersion: v1
kind: ConfigMap
metadata:
  name: modeler-websockets
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: modeler-websockets
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: modeler-websockets
    app.kubernetes.io/part-of: camunda-platform
data:
  php-dev.ini: |-
    log_errors = On
    error_reporting = E_ALL
    display_errors = On
    display_startup_errors = On
