apiVersion: v1
kind: ConfigMap
metadata:
  name: modeler-websockets-env-vars
  namespace: camunda8-dev
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: modeler-websockets
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: modeler-websockets
data:
  APP_DEBUG: "true"
  APP_NAME: Web Modeler Self-Managed WebSockets
  APP_URL: https://webmodeler-ws.example.com # kpt-set: https://webmodeler-ws.${camunda-domain}
  ASSET_URL: https://webmodeler-ws.example.com # kpt-set: https://webmodeler-ws.${camunda-domain}
  CURLOPT_SSL_VERIFYHOST: "FALSE"
  CURLOPT_SSL_VERIFYPEER: "FALSE"
  PUSHER_APP_CLUSTER: camunda-zeebe-gateway:26500 # kpt-set: ${zeebe-host}
  PUSHER_APP_ID: modeler-app
  LOG_LEVEL: "debug"
