apiVersion: v1
kind: Secret
metadata:
  name: camunda-postgresql
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: keycloak-postgresql
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: keycloak-postgresql
    app.kubernetes.io/part-of: camunda-platform
type: Opaque
data:
  postgres-password: "akxic2x0OUNVaQ==" #relevant for internal-postgres only
  password: "RGJYeWRrVnI3cF9TM1dl"
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
