apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'
resources:
- modeler-restapi-configmap.yaml
- modeler-restapi-deployment.yaml
- modeler-restapi-env-vars.yaml
- modeler-restapi-pusher-secret.yaml
- modeler-restapi-secret.yaml
- modeler-restapi-service-account.yaml
- modeler-restapi-service.yaml
