apiVersion: v1
kind: Service
metadata:
  name: modeler-restapi
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: modeler-restapi
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: modeler-restapi
spec:
  ports:
    - name: http-clients
      port: 8085
      targetPort: 8081
    - name: http-management
      port: 8086
      targetPort: 8091
  selector:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: modeler-restapi
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: modeler-restapi
