apiVersion: v1
kind: ConfigMap
metadata:
  name: modeler-restapi-env-vars
  namespace: camunda8-dev
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: modeler-restapi
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: modeler-restapi
data:
  JAVA_OPTIONS: -Xmx128m -Dlogging.level.root=DEBUG -Dlogging.level.org.hibernate=INFO -Djavax.net.ssl.trustStore=/etc/ssl/camunda/trust-store.jks -Djavax.net.ssl.trustStorePassword=demodemo
  LOGGING_LEVEL_IO_CAMUNDA_MODELER: DEBUG
  #RESTAPI_DB_HOST: modeler-db
  #RESTAPI_DB_NAME: modeler-db
  #RESTAPI_DB_PASSWORD: modeler-db-password
  #RESTAPI_DB_PORT: "5432"
  RESTAPI_DB_USER: modeler-db-user # kpt-set: ${webmodeler-postgresql-user}
  RESTAPI_DB_JDBC_URL: jdbc:postgresql://modeler-db:5432/modeler-db # kpt-set: ${webmodeler-postgresql-url}
  RESTAPI_IDENTITY_BASE_URL: https://camunda.example.com/identity # kpt-set: https://camunda.${camunda-domain}/identity
  RESTAPI_MAIL_ENABLE_TLS: "false"
  RESTAPI_MAIL_FROM_ADDRESS: camunda.b2b@swisscom.com
  RESTAPI_MAIL_HOST: mailhog
  RESTAPI_MAIL_PORT: "1025"
  RESTAPI_OAUTH2_TOKEN_AUDIENCE: web-modeler-api
  RESTAPI_OAUTH2_TOKEN_ISSUER: https://camunda.example.com/auth/realms/camunda-platform # kpt-set: https://${keycloak-domain}/auth/realms/camunda-platform
  RESTAPI_OAUTH2_TOKEN_ISSUER_BACKEND_URL: http://camunda-keycloak/auth/realms/camunda-platform # kpt-set: ${keycloak-backend}/auth/realms/camunda-platform
  RESTAPI_PUBLICAPI_OAUTH2_TOKEN_AUDIENCE: web-modeler-public-api
  RESTAPI_PUSHER_APP_ID: modeler-app
  RESTAPI_PUSHER_HOST: modeler-websockets
  RESTAPI_PUSHER_PORT: "8060"
  RESTAPI_SERVER_SHUTDOWN_TIMEOUT: "3000"
  RESTAPI_SERVER_URL: https://webmodeler-api.example.com # kpt-set: https://webmodeler-api.${camunda-domain}
  SPRING_PROFILES_INCLUDE: default-logging
  ZEEBE_CA_CERTIFICATE_PATH: /etc/ssl/trusted-ca/trusted.crt
