kind: Kustomization
metadata: # kpt-merge: /kustomization
  name: kustomization
  annotations:
    config.kubernetes.io/local-config: 'true'
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|kustomization'
resources:
- authorization-policy.yaml
- camunda-virtualservice.yaml
- camunda-webmodeler-api-virtualservice.yaml
- camunda-webmodeler-virtualservice.yaml
- camunda-webmodeler-ws-virtualservice.yaml
- kibana-virtualservice.yaml
- kafka-virtualservice.yaml
- hashicorp-vault-virtualservice.yaml
- request-authentication.yaml
- service-entry.yaml
- zeebe-virtualservice.yaml
