apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: camunda-platform
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    - name: tcp-internal
      port: 9093
      protocol: TCP
      targetPort: kafka-internal
  selector:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: camunda-platform