apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-headless
  namespace: camunda8-dev
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: camunda-platform
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
    - name: tcp-follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: camunda-platform
