apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-onboarding-env-vars
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: customer-onboarding
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: customer-onboarding
data:
  JDK_JAVA_OPTIONS: -Dlogging.level.root=debug -Djavax.net.ssl.trustStore=/etc/ssl/camunda/trust-store.jks -Djavax.net.ssl.trustStorePassword=demodemo
  ZEEBE_CA_CERTIFICATE_PATH: /var/run/tls/ca.crt
  ZEEBE_SECURE_CONNECTION: "true"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  TZ: Europe/Berlin
  # zeebe.client.broker.gateway-address: zeebe.example.com:443
  # zeebe.client.security.plaintext: "false"
  # zeebe.client.cloud.clientId: workflow-manager
  # zeebe.client.cloud.clientSecret: tBuJC8hdrKmju2wOAbsvHtxU4QdeiEMH
  # zeebe.client.cloud.baseUrl: zeebe.example.com:443
  # zeebe.client.cloud.authUrl: https://camunda.example.com/auth/realms/camunda-platform/protocol/openid-connect/token