apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-onboarding
  name: customer-onboarding
spec:
  ports:
    - name: http-clients
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: customer-onboarding
status:
  loadBalancer: {}
