apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "camunda-zeebe"
  labels:
    app: camunda-platform # kpt-set: ${camunda-app-name}
    app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
    app.kubernetes.io/name: zeebe
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: zeebe-broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: camunda-platform # kpt-set: ${camunda-app-name}
      app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
      app.kubernetes.io/name: zeebe
      app.kubernetes.io/instance: camunda
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: zeebe-broker
  serviceName: "camunda-zeebe"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: camunda-platform # kpt-set: ${camunda-app-name}
        app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
        app.kubernetes.io/name: zeebe
        app.kubernetes.io/instance: camunda
        app.kubernetes.io/part-of: camunda-platform
        app.kubernetes.io/component: zeebe-broker
        sidecar.istio.io/inject: "false"
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "26502"
        traffic.sidecar.istio.io/excludeOutboundPorts: "26502"
    spec:
      serviceAccountName: camunda-zeebe
      containers:
      - name: zeebe
        image: camunda/zeebe:8.1.8
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: zeebe-broker-env-vars
        env:
        - name: K8S_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_SERVICE_NAME
          value: "camunda-zeebe"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ZEEBE_BROKER_NETWORK_ADVERTISEDHOST
          value: "$(K8S_NAME).$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc"
        - name: ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS
          value: $(K8S_SERVICE_NAME)-0.$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc:26502, $(K8S_SERVICE_NAME)-1.$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc:26502, $(K8S_SERVICE_NAME)-2.$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc:26502,
        - name: ZEEBE_BROKER_CLUSTER_CLUSTERNAME
          value: camunda-zeebe
        ports:
        - containerPort: 9600
          name: http-monitoring
        - containerPort: 26501
          name: grpc-command
        - containerPort: 26502
          name: grpc-internal
        readinessProbe:
          httpGet:
            path: /ready
            port: 9600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 960m
            memory: 1920Mi
          requests:
            cpu: 800m
            memory: 1200Mi
        volumeMounts:
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: zeebe-broker-data
          mountPath: /usr/local/zeebe/data
        - name: exporters
          mountPath: /exporters
      volumes:
      - name: config
        configMap:
          name: camunda-zeebe
          defaultMode: 492
      - name: exporters
        emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - zeebe-broker
            topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
  - metadata:
      name: zeebe-broker-data
      labels:
        app: camunda-platform # kpt-set: ${camunda-app-name}
        app.kubernetes.io/version: "1.0.0" # kpt-set: ${camunda-app-version}
        app.kubernetes.io/name: zeebe-broker-data
        app.kubernetes.io/instance: camunda
        app.kubernetes.io/part-of: camunda-platform
        app.kubernetes.io/component: zeebe-broker
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: "32Gi"
